services:
  - type: web
    name: contactcleaner
    env: python
    plan: starter
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT app:app
    envVars:
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
      - key: UPLOAD_FOLDER
        value: /tmp/uploads
      - key: PYTHONUNBUFFERED
        value: "1"
    disk:
      name: uploads
      mountPath: /tmp/uploads
      sizeGB: 1 